import test from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import http from 'node:http';
import { commandFor, decodeLine, buildPrompt, briefingText, employees } from '../adapters.mjs';

test('Adaptadores mantêm prompts como dados e sinalizam falhas e permissões', () => {
  const injection = 'pedido; touch /tmp/nao-executar $(id)';
  for (const provider of ['claude', 'codex', 'bob']) {
    const c = commandFor(provider, '/tmp/projeto com espaço', injection);
    assert.ok(c.input === injection || c.args.includes(injection));
    assert.ok(!c.args.some(a => a.includes('bypass') || a === '--trust' || a === '--accept-license'));
  }
  const claude = commandFor('claude', '/tmp/projeto', 'pedido');
  /* O terminal dos funcionários é liberado, mas publicar, virar root e apagar em massa continuam barrados. */
  assert.ok(claude.args.includes('--allowed-tools'));
  assert.match(claude.args.join(' '), /Bash/);
  assert.ok(!claude.args.join(' ').includes('bypassPermissions'));
  for (const proibido of ['sudo', 'git push', 'rm -rf', 'rm -fr']) {
    assert.match(claude.args.join(' '), new RegExp(`Bash\\(${proibido}:\\*\\)`));
    assert.match(claude.args.join(' '), new RegExp(`Bash\\(${proibido} \\*\\)`));
  }
  {
  }
  assert.equal(decodeLine('{"type":"result","is_error":true,"result":"sem login"}').failed, true);
  assert.equal(decodeLine('{"type":"result","permission_denials":[{}]}').blocked, true);
  assert.equal(decodeLine('{"type":"turn.failed","error":{"message":"quota"}}').failed, true);
  assert.equal(decodeLine('{"type":"error","message":"usage limit reached"}').exhausted, true);
  assert.equal(decodeLine('{"type":"rate_limit_event","rate_limit_info":{"status":"allowed","rateLimitType":"five_hour","overageStatus":"rejected"}}').exhausted, false);
  assert.equal(decodeLine('{"type":"rate_limit_event","rate_limit_info":{"status":"rejected","rateLimitType":"five_hour"}}').exhausted, true);
  assert.equal(decodeLine('{"type":"assistant","message":{"content":[{"type":"text","text":"A etapa falhou porque esgotou o rate limit da outra API."}]}}').exhausted, false);
  assert.equal(decodeLine('{"type":"result","result":"Revisei o trecho sobre limite de tokens."}').exhausted, false);
  assert.equal(decodeLine('{"type":"message","role":"user","content":"PEDIDO DO USUÁRIO: nao mostre isto"}').text, '');
  assert.deepEqual(decodeLine('{"type":"message","role":"assistant","content":"ola"}'), { text:'ola', result:'ola', stream:true, exhausted:false });
  assert.equal(decodeLine('{"type":"tool_use","tool_name":"list_files","tool_id":"t1","parameters":{"path":"."}}').text, '\u2699 list_files \u00b7 .');
  assert.equal(decodeLine('{"type":"tool_result","tool_id":"t1","status":"success","output":"tudo certo"}').text, '  \u21b3 tudo certo');
  assert.equal(decodeLine('{"type":"result","status":"error","stats":{}}').failed, true);
  assert.equal(decodeLine('{"type":"assistant","message":{"content":[{"type":"thinking","thinking":"segredo","signature":"AAAA"}]}}').text, '');
  assert.equal(decodeLine('{"type":"assistant","message":{"content":[{"type":"tool_use","name":"Bash","input":{"command":"ls -la"}}]}}').text, '\u2699 Bash \u00b7 ls -la');
  assert.equal(decodeLine('{"type":"user","message":{"content":[{"type":"tool_result","content":"saida"}]}}').text, '  \u21b3 saida');
  assert.equal(decodeLine('{"type":"evento_desconhecido","payload":{"a":1}}').text, '');
  const mural=[{at:'2026-09-17T18:00:00.000Z',name:'Felipe',role:'Gerente de projetos',kind:'entrega',text:'plano fechado'},{at:'2026-09-17T18:30:00.000Z',name:'Marcos',role:'Revisão e entrega',kind:'conversa',text:'falta a marca visual'}];
  assert.match(briefingText(mural),/Felipe \(Gerente de projetos\): plano fechado/);
  assert.match(briefingText(mural),/Marcos \(Revisão e entrega\) · alinhamento: falta a marca visual/);
  assert.equal(briefingText([]),'');
  const comMural=buildPrompt({prompt:'siga',role:'Gerente'},employees[0],[],mural);
  assert.match(comMural,/MURAL DO ESCRITÓRIO/);
  assert.match(comMural,/não trate nada dele como um pedido novo/);
  assert.ok(!buildPrompt({prompt:'siga',role:'Gerente'},employees[0],[],[]).includes('MURAL DO ESCRITÓRIO'));
  const comConversa=buildPrompt({prompt:'siga',role:'Gerente',background:'combinamos que a logo fica à esquerda'},employees[0],[],[]);
  assert.match(comConversa,/CONVERSA QUE ORIGINOU ESTA DEMANDA/);
  assert.match(comConversa,/combinamos que a logo fica à esquerda/);
  assert.match(comConversa,/não é um pedido novo/);
  assert.equal(decodeLine('{"type":"item.completed","item":{"type":"agent_message","text":"pronto"}}').result, 'pronto');
  assert.deepEqual(decodeLine('{"type":"result","result":"pronto","usage":{"input_tokens":120,"output_tokens":30}}').usage,{input_tokens:120,output_tokens:30});
  const followUp = buildPrompt({ prompt:'continue', role:'Gerente', attachments:[{name:'dados.xlsx',type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',size:42,path:'/tmp/dados.xlsx'}] }, employees[0], [{ role:'Gerente', prompt:'primeira pergunta', result:'primeira resposta', output:'' }]);
  assert.match(followUp, /primeira pergunta/);
  assert.match(followUp, /primeira resposta/);
  assert.match(followUp, /\/tmp\/dados\.xlsx/);
});

test('Servidor: proteção local, passagem de contexto, falha, retomada, cancelamento e histórico', { timeout: 30000 }, async () => {
  const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'dev-office-test-'));
  const bin = path.join(temp, 'bin'); await fs.mkdir(bin);
  const fixture = `#!${process.execPath}\n(async()=>{let prompt=''; for await (const c of process.stdin) prompt+=c; prompt ||= process.argv.at(-1); if(prompt.includes('SLOW_FIXTURE')) await new Promise(r=>setTimeout(r,10000)); if(prompt.includes('DENIED_FIXTURE')) {console.log(JSON.stringify({type:'result',result:'entreguei mesmo assim',permission_denials:[{tool_name:'Bash'}]}));process.exit(0);} if(prompt.includes('BARRADO_FIXTURE')) {console.log(JSON.stringify({type:'result',result:'',permission_denials:[{tool_name:'Bash'}]}));process.exit(0);} if(prompt.includes('EQUIPE (use exatamente estes ids)')) {const plano={resumo:'UX primeiro, backend solto, frontend depois do alinhamento.',etapas:[{id:'e1',employee:'architect',tarefa:'ALINHAR_FIXTURE desenhe o fluxo e entregue as telas.',depende:[]},{id:'e2',employee:'backend',tarefa:'Implemente a API de leitura.',depende:[]},{id:'e3',employee:'frontend',tarefa:'Implemente a tela com o UX aprovado.',depende:['a1']}],alinhamentos:[{id:'a1',participantes:['architect','frontend'],pauta:'Passar o UX pronto para a implementacao.',depende:['e1']}]};console.log(JSON.stringify({type:'result',result:JSON.stringify(plano)}));process.exit(0);} if(prompt.startsWith('Você é Vinicius') && prompt.includes('ALINHAR_FIXTURE')) {console.log(JSON.stringify({type:'result',result:'Telas entregues.\\nALINHAR: backend \u2014 preciso combinar o contrato de dados'}));process.exit(0);} if(prompt.includes('MURAL_CHECK')) {console.log(JSON.stringify({type:'result',result: prompt.includes('MURAL DO ESCRIT\u00d3RIO')?'mural: sim':'mural: nao'}));process.exit(0);} if(prompt.includes('STREAM_FIXTURE')) {console.log(JSON.stringify({type:'message',role:'user',content:prompt}));console.log(JSON.stringify({type:'tool_use',tool_name:'list_files',tool_id:'t1',parameters:{path:'.'}}));console.log(JSON.stringify({type:'tool_result',tool_id:'t1',status:'success',output:'nada aqui'}));for(const part of ['ola',' mun','do']) console.log(JSON.stringify({type:'message',role:'assistant',content:part}));console.log(JSON.stringify({type:'result',status:'success',stats:{}}));process.exit(0);} if(prompt.includes('QUOTA_FIXTURE')) {console.log(JSON.stringify({type:'error',message:'usage limit reached'}));process.exit(1);} if(prompt.includes('FAIL_FIXTURE')) {console.log(JSON.stringify({type:'result',is_error:true,result:'falha esperada'}));process.exit(0);} console.log(JSON.stringify({type:'result',result:prompt.includes('CONTEXTO DAS ETAPAS ANTERIORES:')?'contexto recebido':'primeira etapa'}));})();`;
  for (const name of ['claude','codex','bob']) await fs.writeFile(path.join(bin, name), fixture, { mode: 0o755 });
  let child;
  const port = 14317;
  const origin = `http://127.0.0.1:${port}`;
  async function boot() {
    child = spawn(process.execPath, ['server.mjs'], { cwd: new URL('..', import.meta.url), env: { ...process.env, PORT: String(port), OFFICE_DATA_DIR: path.join(temp, 'data'), PATH: bin, BOB_API_KEY: 'fixture-only-not-a-real-key' }, stdio: ['ignore', 'pipe', 'pipe'] });
    await Promise.race([once(child.stdout,'data'), once(child,'exit').then(()=>{throw new Error('Servidor não iniciou');})]);
    const b = await (await fetch(`${origin}/api/bootstrap`)).json(); return b.token;
  }
  async function stop() { const ended = once(child, 'exit'); child.kill('SIGTERM'); await ended; }
  let token;
  const read = async () => (await fetch(`${origin}/api/bootstrap`)).json();
  const post = async (route, data, custom = {}) => {
    const r = await fetch(`${origin}/api/${route}`, { method:'POST', headers:{ 'Content-Type':'application/json', 'X-Office-Token':token, ...custom }, body:JSON.stringify(data) });
    return { status:r.status, data:await r.json() };
  };
  async function waitFor(predicate) { for(let i=0;i<120;i++){ const s=await read(); if(predicate(s)) return s; await new Promise(r=>setTimeout(r,50)); } throw new Error('Estado esperado não chegou: ' + JSON.stringify((await read()).tasks.map(t=>({status:t.status,output:t.output})))); }
  try {
    token = await boot();
    assert.equal((await post('pause',{paused:true},{Origin:'https://externo.example'})).status,403);
    assert.equal((await post('pause',{paused:true},{'X-Office-Token':'errado'})).status,403);
    assert.equal((await fetch(`${origin}/.office/state.json`)).status,404);
    assert.equal((await fetch(`${origin}/.office/spotify.json`)).status,404);
    const musicState=await post('spotify/status',{});
    assert.equal(musicState.status,200);
    assert.equal(musicState.data.connected,false);
    assert.equal((await post('spotify/control',{action:'play'},{'X-Office-Token':'errado'})).status,403);
    assert.equal((await post('spotify/connect',{clientId:'invalid'})).status,400);
    const connectSpotify=await fetch(`${origin}/api/spotify/connect`,{method:'POST',headers:{'Content-Type':'application/json','X-Office-Token':token},body:JSON.stringify({clientId:'a'.repeat(32)})});
    assert.match(connectSpotify.headers.get('set-cookie'),/HttpOnly/);
    const authorization=await connectSpotify.json();assert.equal(new URL(authorization.url).hostname,'accounts.spotify.com');
    const invalidCallback=await fetch(`${origin}/spotify/callback?state=wrong&code=unused`,{redirect:'manual',headers:{'sec-fetch-site':'cross-site'}});
    assert.equal(invalidCallback.status,303);assert.equal(invalidCallback.headers.get('location'),'/?spotify=error');
    const redirectedNavigation={'sec-fetch-site':'cross-site','sec-fetch-mode':'navigate','sec-fetch-dest':'document'};
    // Node fetch replaces Sec-Fetch-Mode with cors; send real navigation headers.
    const navigate = route => new Promise((resolve,reject)=>{
      http.get(`${origin}${route}`,{headers:redirectedNavigation},res=>{
        let text='';res.setEncoding('utf8');res.on('data',chunk=>text+=chunk);
        res.on('end',()=>resolve({status:res.statusCode,text}));
      }).on('error',reject);
    });
    for(const result of ['connected','error']) {
      const landing=await navigate(`/?spotify=${result}`);
      assert.equal(landing.status,200);
      assert.match(landing.text,/id="office-canvas"/);
    }
    assert.equal((await fetch(`${origin}/?spotify=connected`,{headers:{'sec-fetch-site':'cross-site'}})).status,403);
    assert.equal((await navigate('/api/bootstrap')).status,403);
    assert.equal((await post('spotify/control',{action:'play'},{...redirectedNavigation})).status,403);
    assert.equal((await post('spotify/status',{})).data.connected,false);
    for (const route of ['/spotify-radio.js','/office3d.js','/office-motion.js','/vendor/three.module.min.js','/vendor/three.core.min.js','/vendor/GLTFLoader.js','/vendor/utils/BufferGeometryUtils.js']) {
      const asset = await fetch(`${origin}${route}`);
      assert.equal(asset.status,200,`rota ${route}`);
      assert.match(asset.headers.get('content-type'),/javascript/);
      assert.ok((await asset.arrayBuffer()).byteLength>0,`conteúdo de ${route}`);
    }
    const model = await fetch(`${origin}/assets/kenney/character-a.glb`);
    assert.equal(model.status,200);
    assert.match(model.headers.get('content-type'),/model\/gltf-binary/);
    assert.ok((await model.arrayBuffer()).byteLength > 100000);
    const animated = await fetch(`${origin}/assets/blender/employee.glb`);
    assert.equal(animated.status,200);
    assert.match(animated.headers.get('content-type'),/gltf-binary/);
    assert.equal((await fetch(`${origin}/vendor/LICENSE`)).status,404);
    const page = await (await fetch(`${origin}/`)).text();
    assert.match(page,/id="office-canvas"/);
    assert.match(page,/id="employee-chat-form"/);
    assert.match(page,/id="meeting-dialog"/);
    assert.ok(!page.includes('office.png'));
    const assignments={manager:'claude',architect:'claude',frontend:'codex',backend:'codex',qa:'bob',delivery:'bob'};
    assert.equal((await post('config',{workspace:'relativo',assignments,standup:false})).status,400);
    assert.equal((await post('config',{workspace:temp,assignments,standup:false})).status,200);
    await post('pause',{paused:true});
    await post('missions',{employee:'team',prompt:'Construa um teste de integração.'});
    assert.equal((await read()).tasks.filter(t=>t.status==='queued').length,6);
    await post('pause',{paused:false});
    let s=await waitFor(s=>s.tasks.every(t=>t.status==='done'));
    assert.equal(s.tasks[0].result,'primeira etapa');
    assert.ok(s.tasks.slice(1).every(t=>t.result==='contexto recebido'));
    await post('missions',{participants:['manager','frontend'],prompt:'Discutam juntos esta demanda.'});
    s=await waitFor(s=>s.tasks.slice(-2).every(t=>t.status==='done'));
    assert.ok(s.tasks.slice(-2).every(t=>t.meeting===true));
    assert.deepEqual(s.tasks.at(-1).participants,['manager','frontend']);
    assert.equal(s.tasks.at(-1).result,'contexto recebido');
    await post('missions',{employee:'team',prompt:'FAIL_FIXTURE pedido com falha.'});
    s=await waitFor(s=>s.tasks.some(t=>t.status==='failed'));
    assert.equal(s.tasks.filter(t=>t.status==='blocked').length,5);
    await post('archive',{mission:s.tasks.find(t=>t.status==='failed').mission});
    await post('missions',{employee:'frontend',prompt:'Analise esta planilha como contexto.',attachments:[{name:'dados.csv',type:'text/csv',data:Buffer.from('coluna\nvalor').toString('base64')}]});
    s=await waitFor(s=>s.tasks.at(-1).status==='done');
    assert.equal(s.tasks.at(-1).chat,true);
    assert.equal(s.tasks.at(-1).attachments[0].name,'dados.csv');
    assert.equal(await fs.readFile(s.tasks.at(-1).attachments[0].path,'utf8'),'coluna\nvalor');
    await post('missions',{employee:'qa',prompt:'STREAM_FIXTURE responda em pedaços.'});
    s=await waitFor(s=>s.tasks.at(-1).status==='done');
    assert.equal(s.tasks.at(-1).result,'ola mundo');
    assert.ok(!s.tasks.at(-1).output.includes('PEDIDO DO USUÁRIO'));
    assert.match(s.tasks.at(-1).output,/\u2699 list_files \u00b7 \./);
    assert.match(s.tasks.at(-1).output,/\u21b3 nada aqui/);
    assert.equal((await post('config',{workspace:temp,assignments,standup:true})).status,200);
    await post('missions',{participants:['manager','architect'],prompt:'Combine o plano de entrega desta etapa.'});
    s=await waitFor(s=>s.tasks.filter(t=>t.standup).length===2 && s.tasks.filter(t=>t.standup).every(t=>t.status==='done'));
    const alinhamento=s.tasks.filter(t=>t.standup);
    assert.deepEqual(alinhamento.map(t=>t.employee),['manager','architect']);
    assert.ok(alinhamento.every(t=>t.meeting && t.about===s.tasks.find(t=>t.prompt.startsWith('Combine o plano')).mission));
    assert.ok(s.briefing.some(entry=>entry.kind==='conversa'));
    assert.ok(s.briefing.some(entry=>entry.kind==='entrega'));
    await post('missions',{employee:'frontend',prompt:'MURAL_CHECK o mural chegou ate mim?'});
    s=await waitFor(s=>s.tasks.at(-1).status==='done');
    assert.equal(s.tasks.at(-1).result,'mural: sim');
    assert.equal(s.tasks.filter(t=>t.standup).length,2);
    assert.equal((await post('config',{workspace:temp,assignments,standup:false})).status,200);
    await post('missions',{participants:['manager','architect'],prompt:'Precisamos de uma tela nova com backend e UX.'});
    s=await waitFor(s=>s.tasks.slice(-2).every(t=>t.status==='done'));
    const reuniao=s.tasks.at(-1).mission;
    const rascunho=await post('plan',{mission:reuniao});
    assert.equal(rascunho.status,200);
    assert.deepEqual(rascunho.data.plan.etapas.map(e=>e.employee),['architect','backend','frontend']);
    assert.deepEqual(rascunho.data.plan.alinhamentos[0].participantes,['architect','frontend']);
    assert.equal((await read()).tasks.filter(t=>t.plan).length,0);
    assert.equal((await post('plan/confirm',{mission:reuniao,plan:rascunho.data.plan})).status,200);
    s=await waitFor(s=>s.tasks.filter(t=>t.plan).length>=5 && s.tasks.filter(t=>t.plan).every(t=>['done','failed','blocked'].includes(t.status)));
    const doPlano=s.tasks.filter(t=>t.plan);
    assert.equal(doPlano.filter(t=>t.meeting && !t.asked).length,2);
    const pedida=doPlano.filter(t=>t.asked);
    assert.deepEqual(pedida.map(t=>t.employee),['architect','backend']);
    const primeiroAlinhamento=doPlano.find(t=>t.meeting && !t.asked && t.employee==='architect');
    assert.ok(primeiroAlinhamento.depends.some(id=>pedida.some(p=>p.id===id)));
    const porId=new Map(s.tasks.map(t=>[t.id,t]));
    for (const t of s.tasks.filter(t=>t.depends?.length && t.startedAt)) for (const dep of t.depends) {
      const anterior=porId.get(dep);
      assert.ok(anterior?.endedAt && new Date(anterior.endedAt)<=new Date(t.startedAt), `${t.name} comecou antes de ${anterior?.name}`);
    }
    await post('missions',{participants:['qa','delivery'],prompt:'Conversem rapidamente sobre o estado da entrega.'});
    s=await waitFor(s=>s.tasks.slice(-2).every(t=>t.status==='done'));
    const conversa=s.tasks.at(-1).mission, rodada=s.tasks.at(-1).round;
    assert.ok(rodada);
    assert.equal((await post('meeting/close',{round:rodada})).status,200);
    s=await read();
    assert.ok(s.tasks.filter(t=>t.round===rodada).every(t=>t.closed===true));
    assert.equal((await post('finish',{mission:conversa})).status,200);
    s=await waitFor(s=>s.finished.includes(conversa) && s.tasks.some(t=>t.standup && t.about===conversa) && !s.tasks.some(t=>['queued','running'].includes(t.status)));
    assert.deepEqual(s.tasks.filter(t=>t.standup && t.about===conversa).map(t=>t.employee),['qa','delivery']);
    assert.equal((await post('finish',{mission:conversa})).status,400);
    assert.ok(s.briefing.some(entry=>entry.mission===conversa));
    assert.equal((await post('delete',{mission:conversa})).status,200);
    s=await read();
    assert.equal(s.tasks.filter(t=>t.mission===conversa).length,0);
    assert.ok(!s.briefing.some(entry=>entry.mission===conversa));
    assert.ok(!s.finished.includes(conversa));
    await post('pause',{paused:true});
    await post('missions',{employee:'team',prompt:'Demanda que vou encerrar antes de começar.'});
    const abandonada=(await read()).tasks.at(-1).mission;
    assert.equal((await post('finish',{mission:abandonada})).status,200);
    s=await read();
    assert.ok(s.tasks.filter(t=>t.mission===abandonada).every(t=>t.status==='cancelled'));
    assert.ok(s.finished.includes(abandonada));
    assert.equal((await post('retry',{id:s.tasks.find(t=>t.mission===abandonada).id})).status,400);
    assert.equal((await post('archive',{mission:abandonada})).status,200);
    assert.equal((await read()).tasks.filter(t=>t.mission===abandonada).length,0);
    await post('pause',{paused:false});
    const daConversa=await post('plan',{employee:'frontend'});
    assert.equal(daConversa.status,200);
    assert.equal(daConversa.data.employee,'frontend');
    assert.equal(daConversa.data.mission,null);
    assert.match(daConversa.data.background,/Você pediu/);
    const antesDoPlano=(await read()).tasks.length;
    assert.equal((await post('plan/confirm',{employee:'frontend',background:daConversa.data.background,plan:daConversa.data.plan})).status,200);
    s=await read();
    const novas=s.tasks.slice(antesDoPlano);
    assert.ok(novas.length>=5);
    assert.ok(novas.every(t=>t.plan && t.background.includes('Você pediu')));
    assert.equal(new Set(novas.map(t=>t.mission)).size,1);
    s=await waitFor(s=>!s.tasks.some(t=>['queued','running'].includes(t.status)));
    await post('missions',{participants:['manager','architect','qa'],prompt:'DENIED_FIXTURE conversem sobre a entrega.'});
    s=await waitFor(s=>s.tasks.slice(-3).every(t=>!['queued','running'].includes(t.status)));
    const comNegativa=s.tasks.slice(-3);
    assert.deepEqual(comNegativa.map(t=>t.status),['done','done','done']);
    assert.ok(comNegativa.every(t=>t.denied===true && t.result==='entreguei mesmo assim'));
    assert.equal(s.briefing.filter(e=>e.text==='entreguei mesmo assim').length,3);
    await post('missions',{employee:'manager',prompt:'BARRADO_FIXTURE nao consegui entregar nada.'});
    s=await waitFor(s=>!['queued','running'].includes(s.tasks.at(-1).status));
    assert.equal(s.tasks.at(-1).status,'blocked');
    assert.ok(!s.tasks.at(-1).denied);
    await post('pause',{paused:true});
    await post('missions',{employee:'team',prompt:'Fila para reordenar pelo mural.'});
    let fila=(await read()).tasks.filter(t=>t.status==='queued');
    assert.equal(fila.length,6);
    const ultimo=fila[5];
    assert.equal((await post('task/move',{id:ultimo.id,beforeId:fila[0].id})).status,200);
    fila=(await read()).tasks.filter(t=>t.status==='queued');
    assert.equal(fila[0].id,ultimo.id);
    assert.equal(fila.length,6);
    assert.equal((await post('task/move',{id:ultimo.id,beforeId:null})).status,200);
    assert.equal((await read()).tasks.filter(t=>t.status==='queued').at(-1).id,ultimo.id);
    const alvo=(await read()).tasks.filter(t=>t.status==='queued')[2];
    assert.equal((await post('task/cancel',{id:alvo.id})).status,200);
    s=await read();
    assert.equal(s.tasks.find(t=>t.id===alvo.id).status,'cancelled');
    assert.equal(s.tasks.filter(t=>t.status==='queued').length,5);
    assert.equal((await post('task/retry',{id:alvo.id})).status,200);
    assert.equal((await read()).tasks.filter(t=>t.status==='queued').length,6);
    assert.equal((await post('task/move',{id:s.tasks.find(t=>t.status==='done').id,beforeId:null})).status,400);
    await post('cancel',{id:ultimo.id});
    await post('pause',{paused:false});
    await post('missions',{employee:'backend',prompt:'FAIL_FIXTURE etapa que para com falha.'});
    s=await waitFor(s=>s.tasks.at(-1).status==='failed');
    const queFalhou=s.tasks.at(-1);
    /* Encerrar sem retomar vale para quem parou com falha: era o que o mural recusava. */
    assert.equal((await post('task/cancel',{id:queFalhou.id})).status,200);
    s=await read();
    assert.equal(s.tasks.find(t=>t.id===queFalhou.id).status,'cancelled');
    assert.equal((await post('task/cancel',{id:queFalhou.id})).status,400);
    assert.equal((await post('task/cancel',{id:s.tasks.find(t=>t.status==='done').id})).status,400);
    s=await waitFor(s=>!s.tasks.some(t=>['queued','running'].includes(t.status)));
    await post('missions',{employee:'manager',prompt:'QUOTA_FIXTURE simule tokens esgotados.'});
    s=await waitFor(s=>s.tasks.at(-1).status==='failed');
    assert.equal(s.tasks.at(-1).exhausted,true);
    await post('missions',{employee:'frontend',prompt:'SLOW_FIXTURE teste de cancelamento.'});
    s=await waitFor(s=>s.tasks.some(t=>t.status==='running'));
    const slow=s.tasks.find(t=>t.status==='running');
    assert.equal((await post('config',{workspace:temp,assignments})).status,400);
    await post('cancel',{id:slow.id});
    await waitFor(s=>s.tasks.at(-1).status==='cancelled' && !!s.tasks.at(-1).endedAt);
    await post('retry',{id:slow.id});
    await waitFor(s=>s.tasks.at(-1).status==='running');
    await stop(); token=await boot();
    s=await read(); assert.equal(s.tasks.at(-1).status,'interrupted');
    assert.equal(s.tasks.filter(t=>t.status==='done').length,36);
  } finally { if(child && child.exitCode===null) await stop(); await fs.rm(temp,{recursive:true,force:true}); }
});
